added terraform files to create stcv VM instances
Spirent-Terraform-Modules/terraform-azurerm-stcv pull request #1
Opened 2021-01-19 18:12 UTC by radhikabhat08

2021-01-19 20:07 UTC, ltran-spirent requested changes
> ```
> resource "azurerm_network_security_group" "test" {
> ```

I think there is an overall readability issue with calling things just `test`

My recommendation is to reevaluate what you want to call resources in this, because the adopted context of `test` generally means temporary code ala unit tests.  

> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-:-MRQvkVq6GaB4k1MlSD2:b-bn36zr)* status: 0 of 5 files reviewed, 13 unresolved discussions (waiting on @jhiga, @radhikabhat08, and @rmyers808)

___
*[main.tf, line 10 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQujZODP82QagyceR_:-MRQujZP3treTzCS5WAF:b-dv1yq4) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L10)):*
> ```HCL
> data "azurerm_subnet" "mgmt" {
>   name                 = var.mgmt_subnet
>   virtual_network_name = var.vnet
> ```

`vnet_name` or `virtual_network_name` or something more contextual
___
*[main.tf, line 20 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQv0DACIoD9prWWo6M:-MRQv0DACIoD9prWWo6N:bioca9a) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L20)):*
> ```HCL
> }
> 
> resource "azurerm_public_ip" "stcv_publicip" {
> ```

Don't repeat the `publicip` in the name, since this is a resource already defined as `azurerm_public_ip`. It's redundant.
___
*[main.tf, line 29 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQvP4WASXqfP628yHs:-MRQvP4WASXqfP628yHt:bqp5nfd) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L29)):*
> ```HCL
> 
> resource "azurerm_network_security_group" "mgmt" {
>   name                = "mgmtnsg-${var.vm_hostname}"
> ```

I would recommend `nsg-mgmt-${var.vm_hostname}` so it can be grouped together in the admin
___
*[main.tf, line 59 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQvAOU28u1kVIiVPBw:-MRQvAOU28u1kVIiVPBx:bwaf169) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L59)):*
> ```HCL
> 
>   security_rule {
>     name                       = "stcvport"
> ```

You title cased previous rule names, but this is all lowercase.  Please use a single convention
___
*[main.tf, line 72 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQvfUL9hNraMTI9zmM:-MRQvfUL9hNraMTI9zmN:bqt7x7s) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L72)):*
> ```HCL
> 
> resource "azurerm_network_security_group" "test" {
>   name                = "testnsg-${var.vm_hostname}"
> ```

I would recommend `nsg-test-${var.vm_hostname}` so it can be grouped together in the admin
___
*[main.tf, line 85 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQwT954I3OG7fqoElS:-MRQwT954I3OG7fqoElT:b-hsi9bd) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L85)):*
> ```
> source_address_prefix      = var.ingress_cidr_blocks
> ```

Does not match the definition of what ingress_cidr_blocks are per README.  Why are we using this as source addresses? Especially when talking about egress traffic
___
*[main.tf, line 90 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQwY2TA_2bXFiWk8ku:-MRQwY2TA_2bXFiWk8kv:b-z1f0rk) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L90)):*
> ```HCL
> }
> 
> resource "azurerm_network_interface" "mgmt_nic" {
> ```

no need to include `nic` in the name
___
*[main.tf, line 109 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQwbvA25PBp2q8xgqg:-MRQwbvA25PBp2q8xgqh:br0u2uj) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L109)):*
> ```HCL
>   location                      = var.resource_group_location
>   resource_group_name           = var.resource_group_name
>   enable_accelerated_networking = var.enable_accelerated_networking_flag
> ```

drop the `_flag` in the variable name
___
*[main.tf, line 112 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQwh_33BZ2Wln4T6Sr:-MRQwh_33BZ2Wln4T6Ss:btwt9r9) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L112)):*
> ```HCL
> 
>   ip_configuration {
>     name                          = "testipconfig-${var.vm_hostname}-${count.index}"
> ```

`ipc-test-...`

ipconfig seems verbose
___
*[outputs.tf, line 3 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQxRm-3Q64ewwxE3ED:-MRQxRm-3Q64ewwxE3EE:blo359j) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/outputs.tf#L3)):*
> ```HCL
> # OUTPUTS
> 
> output "vm_public_ip" {
> ```

nit: this is a list of IPs, not a single IP
___
*[outputs.tf, line 8 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQxVUWDbeahIxMmQmG:-MRQxVUWDbeahIxMmQmH:blo359j) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/outputs.tf#L8)):*
> ```HCL
> }
> 
> output "vm_private_ip" {
> ```

nit: this is a list of IPs, not a single IP
___
*[variables.tf, line 57 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRRFY0t0lEgJu4OMjR6:-MRRFY0u4wKXHcGUN80m:b1etz3h) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/variables.tf#L57)):*
> ```HCL
> }
> 
> variable "enable_accelerated_networking_flag" {
> ```

`variable "enable_accelerated_networking"`
___
*[variables.tf, line 76 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQxAu4B1x09lJd039D:-MRQxAu4B1x09lJd039E:b2y7jve) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/variables.tf#L76)):*
> ```HCL
> 
> variable "public_key" {
>   description = "Contents of public key."
> ```

These are contents, this is a file path


<!-- Sent from Reviewable.io -->

2021-01-20 01:14 UTC, jhiga requested changes
@ltran-spirent - Is it conventional to prefix the component (e.g. `stcv_test_traffic`) in front of resource names or is something like `test_traffic` and `mgmt_traffic` preferred?

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-:-MRSGwJkBkTVAONLRcjR:bj08wcu)* status: all files reviewed, 17 unresolved discussions (waiting on @radhikabhat08 and @rmyers808)

___
*[cloud-init.yaml, line 2 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRSHV8w6d3DHKgh1AvX:-MRSHV8w6d3DHKgh1AvY:b-qu0j7m) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/cloud-init.yaml#L2)):*
> ```YAML
> #cloud-config
> # uncomment below spirent block to set 1G speed
> ```

You can remove this line.
___
*[main.tf, line 14 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRSIyVvCTcVs7eKwHJD:-MRSIyVw6K6U5FF_njSo:b-e7k5bi) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L14)):*
> ```HCL
> }
> 
> data "azurerm_subnet" "test" {
> ```

`test` -> `test_traffic`
___
*[outputs.tf, line 13 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRSKIPc2oT06Nq-HUKq:-MRSKIPdCu8GA96RPmBY:b-wjenzr) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/outputs.tf#L13)):*
> ```HCL
> }
> 
> output "id" {
> ```

`id` -> `vm_ids`
___
*[variables.tf, line 81 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRSLEW63JpaeSpjygur:-MRSLEW7E6o5hZJ4yEcA:bcfjajt) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/variables.tf#L81)):*
> ```HCL
> }
> 
> variable "marketplace_publishername" {
> ```

@ltran-spirent  - Do you think `publishername`, `offer`, and `sku` need to be exposed as variables?  Since this is specific to STCv, I don't think this will ever change.  Only the  `marketplace_version` will change.


<!-- Sent from Reviewable.io -->

2021-01-20 01:18 UTC, ltran-spirent reviewed
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1)* status: all files reviewed, 17 unresolved discussions (waiting on @jhiga, @radhikabhat08, and @rmyers808)

___
*[variables.tf, line 81 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRSLEW63JpaeSpjygur:-MRSMRTE2TH-FgMjipHJ:b-ncno0d) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/variables.tf#L81)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

@ltran-spirent  - Do you think `publishername`, `offer`, and `sku` need to be exposed as variables?  Since this is specific to STCv, I don't think this will ever change.  Only the  `marketplace_version` will change.
</blockquote></details>

@jhiga Good point.  Considering this work is specific to STCv, we should hard code it in.


<!-- Sent from Reviewable.io -->

2021-01-20 01:22 UTC, ltran-spirent reviewed
@jhiga I think @rmyers808 has the right idea with the example.  (see https://github.com/Spirent-Terraform-Modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/examples/run-stcv-2instances/main.tf#L6)

so when referencing the module resources, it would read `module.stcv.subnet.mgmt_traffic` for example.  That to me is more readable than `module.stcv.subnet.stcv_test_traffic`

> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-:-MRSN4Oy5g7OP04G91xy:b-ig2u3d)* status: all files reviewed, 17 unresolved discussions (waiting on @jhiga, @radhikabhat08, and @rmyers808)



<!-- Sent from Reviewable.io -->

2021-01-20 01:26 UTC, jhiga reviewed
:+1: when you spell it out, makes sense.  @radhikabhat08 let's go with `test_traffic`

> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-:-MRSOA3Q-2qVFbqCjw3d:boea53s)* status: all files reviewed, 17 unresolved discussions (waiting on @jhiga, @radhikabhat08, and @rmyers808)



<!-- Sent from Reviewable.io -->

2021-01-20 18:05 UTC, radhikabhat08 commented
I have addressed the review comments. Please take a look.

2021-01-20 21:39 UTC, jhiga requested changes
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1)* status: all files reviewed, 25 unresolved discussions (waiting on @radhikabhat08 and @rmyers808)

___
*[main.tf, line 33 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWK6o-8C8eooFU9XJq:-MRWK6o08kSNqmD1FqHY:b-wm5cs5) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/main.tf#L33)):*
> ```HCL
> 
>   security_rule {
>     name                       = "chassis"
> ```

chassis -> stc-chassis
___
*[main.tf, line 45 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWK-a68XsKEmzU3ZNm:-MRWK-a68XsKEmzU3ZNn:byzhwfn) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/main.tf#L45)):*
> ```HCL
> 
>   security_rule {
>     name                       = "stc-app"
> ```

stc-app -> stc-portgroup
___
*[main.tf, line 75 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWJe8KE7oMChTt23oY:-MRWJe8KE7oMChTt23oZ:bb0rbe) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/main.tf#L75)):*
> ```HCL
>   }
> 
>   security_rule {
> ```

These egress rules for `bll_ephemeral` and `ntp` belong under the `mgmt_plane` security group; not `test_plane`.
___
*[README.md, line 50 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWM3c1AnF5bzJTUCx_:-MRWM3c1AnF5bzJTUCxa:bmk3e9s) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/README.md#L50)):*
> ```Markdown
> 
> <!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
> ```

Please remove extra space characters throughout the document
___
*[variables.tf, line 16 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWMTO38W-4pbqVa0HY:-MRWMTO38W-4pbqVa0HZ:b-hd65jc) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/variables.tf#L16)):*
> ```HCL
> variable "instance_count" {
>   type        = string
>   description = "Number of STCv instances to create.."
> ```

Extra period.
___
*[variables.tf, line 53 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWi_3G3xbDeFZZ1hNb:-MRWi_3G3xbDeFZZ1hNc:b-gdm1lj) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/variables.tf#L53)):*
> ```HCL
> 
> variable "enable_accelerated_networking" {
>   description = "Flag to enable or disable accelerated networking on network interface"
> ```

Simplify to:  Enable or disable accelerated networking on the network interface.
___
*[variables.tf, line 72 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWh6kh3mZa7OMSczFs:-MRWh6kh3mZa7OMSczFt:b-wi7hlb) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/variables.tf#L72)):*
> ```HCL
> variable "marketplace_version" {
>   type        = string
>   description = "The Spirent TestCenter Virtual image version example 5.15.0106. When not specified, the latest marketplace image will be used. "
> ```

update description:  The Spirent TestCenter Virtual image version (e.g. 5.15.0106). When not specified, ...
___
*[variables.tf, line 76 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWhcw9Aq_HAWR5v7u6:-MRWhcw9Aq_HAWR5v7u7:b9v6xsv) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/variables.tf#L76)):*
> ```HCL
> 
> variable "user_data_file" {
>   description = "File path name containing AWS user data for the instance.  Spirent TestCenter Virtual cloud-init configuration parameters are supported."
> ```

update description: Path to the file containing user data for the instance.  See README for Spirent TestCenter Virtual cloud-init configuration parameters that are supported.
___
*[examples/run-stcv-2instances/main.tf, line 17 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWiBGM8zlQoU_sa4Ps:-MRWiBGM8zlQoU_sa4Pt:b-dnamab) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/examples/run-stcv-2instances/main.tf#L17)):*
> ```HCL
> module "stcv" {
>   source                    = "../.."
>   
> ```

Remove extra whitespace chars.


<!-- Sent from Reviewable.io -->

2021-01-20 23:48 UTC, rmyers808 reviewed
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1)* status: all files reviewed, 28 unresolved discussions (waiting on @radhikabhat08)

___
*[main.tf, line 110 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRXA0SX3xXexLCNO0Fl:-MRXA0SYCTmkydJ8cnSx:b-50g3ue) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/main.tf#L110)):*
> ```HCL
>   ip_configuration {
>     name                          = "ipc-mgmt-${var.instance_name}-${count.index}"
>     subnet_id                     = var.mgmt_subnet
> ```

Isn't variable declared as "var.mgmt_plane_subnet"?
___
*[main.tf, line 125 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRXArLc192IwqXt5K-E:-MRXArLc192IwqXt5K-F:b1xssjk) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/main.tf#L125)):*
> ```HCL
>   ip_configuration {
>     name                          = "ipc-test-${var.instance_name}-${count.index}"
>     subnet_id                     = var.test_subnet
> ```

Isn't variable defined as var.test_plane_subnet?
___
*[variables.tf, line 50 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRX8nbq4QlOqWga-P40:-MRX8nbq4QlOqWga-P41:b373vcy) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/variables.tf#L50)):*
> ```HCL
>   type        = string
>   description = "Test or data plane Azure subnet name"
> }
> ```

I think the description should be "subnet id" instead of "subnet name" for mgmt_plane_subnet & test_plane_subnet.


<!-- Sent from Reviewable.io -->

2021-01-20 23:50 UTC, rmyers808 reviewed
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1)* status: all files reviewed, 29 unresolved discussions (waiting on @radhikabhat08)

___
*[variables.tf, line 15 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRXBpmo9iY1g7zHW9XF:-MRXBpmo9iY1g7zHW9XG:b3valir) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/variables.tf#L15)):*
> ```HCL
> 
> variable "instance_count" {
>   type        = string
> ```

Should change type = string to type = number.


<!-- Sent from Reviewable.io -->

2021-01-21 09:01 UTC, rmyers808 reviewed
> Reviewed 4 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1)* status: all files reviewed, 29 unresolved discussions (waiting on @radhikabhat08)

___
*[variables.tf, line 50 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRX8nbq4QlOqWga-P40:-MRZA5wsAZAwunjFlH7S:b-sjgixe) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/variables.tf#L50)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

I think the description should be "subnet id" instead of "subnet name" for mgmt_plane_subnet & test_plane_subnet.
</blockquote></details>

I think captial "ID"seems more standard in docs.  I changed my descriptions to that.


<!-- Sent from Reviewable.io -->

2021-01-21 09:02 UTC, rmyers808 reviewed
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1)* status: all files reviewed, 30 unresolved discussions (waiting on @radhikabhat08)

___
*[outputs.tf, line 14 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRZAUAACCMqke1KqHfj:-MRZAUAACCMqke1KqHfk:b-yw2lf5) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/outputs.tf#L14)):*
> ```HCL
> 
> output "instance_ids" {
>   description = "List of IDs of instances"
> ```

Decided "List of instance IDs"  seems more readable.


<!-- Sent from Reviewable.io -->

2021-01-21 16:40 UTC, radhikabhat08 reviewed
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1)* status: 3 of 11 files reviewed, 28 unresolved discussions (waiting on @jhiga, @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[cloud-init.yaml, line 2 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRSHV8w6d3DHKgh1AvX:-MRXo8R16DBRWO5_kN-M:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/cloud-init.yaml#L2)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

You can remove this line.
</blockquote></details>

Done.
___
*[main.tf, line 10 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQujZODP82QagyceR_:-MRXoBJW2E1htU2zYRZ-:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L10)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

`vnet_name` or `virtual_network_name` or something more contextual
</blockquote></details>

Done.
___
*[main.tf, line 14 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRSIyVvCTcVs7eKwHJD:-MRXoCcd0LemhNPc2zDz:b9hj9tb) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L14)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

`test` -> `test_traffic`
</blockquote></details>

changed to test_plane and mgmt_plane across the script.
___
*[main.tf, line 20 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQv0DACIoD9prWWo6M:-MRXoLJAEYuTJ9fLnlaB:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L20)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

Don't repeat the `publicip` in the name, since this is a resource already defined as `azurerm_public_ip`. It's redundant.
</blockquote></details>

Done.
___
*[main.tf, line 29 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQvP4WASXqfP628yHs:-MRXoMGW0_BXesASA_yf:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L29)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

I would recommend `nsg-mgmt-${var.vm_hostname}` so it can be grouped together in the admin
</blockquote></details>

Done.
___
*[main.tf, line 59 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQvAOU28u1kVIiVPBw:-MRXoO2C5yofIJJgSSEh:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L59)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

You title cased previous rule names, but this is all lowercase.  Please use a single convention
</blockquote></details>

Done.
___
*[main.tf, line 72 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQvfUL9hNraMTI9zmM:-MRXoQbnBRJXW-UIOwF6:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L72)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

I would recommend `nsg-test-${var.vm_hostname}` so it can be grouped together in the admin
</blockquote></details>

Done.
___
*[main.tf, line 85 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQwT954I3OG7fqoElS:-MR_FKHUAQCK_dtjuYPJ:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L85)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

> ```
> source_address_prefix      = var.ingress_cidr_blocks
> ```

Does not match the definition of what ingress_cidr_blocks are per README.  Why are we using this as source addresses? Especially when talking about egress traffic
</blockquote></details>

Done.
___
*[main.tf, line 90 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQwY2TA_2bXFiWk8ku:-MRXpK5I7_E3hnbRg-v9:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L90)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

no need to include `nic` in the name
</blockquote></details>

Done.
___
*[main.tf, line 109 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQwbvA25PBp2q8xgqg:-MR_JKhJCp7o_rhsmOY6:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L109)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

drop the `_flag` in the variable name
</blockquote></details>

Done.
___
*[main.tf, line 112 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRQwh_33BZ2Wln4T6Sr:-MR_JLkh1zTMnOoJOcaa:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/741da246a8b1028a93d3aa9fcbadf0f72580ef1d/main.tf#L112)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

`ipc-test-...`

ipconfig seems verbose
</blockquote></details>

Done.
___
*[main.tf, line 33 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWK6o-8C8eooFU9XJq:-MRXoN5j26ekylPSqCcV:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/main.tf#L33)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

chassis -> stc-chassis
</blockquote></details>

Done.
___
*[main.tf, line 45 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWK-a68XsKEmzU3ZNm:-MRXoinU1CEx-uObLhTf:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/main.tf#L45)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

stc-app -> stc-portgroup
</blockquote></details>

Done.
___
*[main.tf, line 75 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWJe8KE7oMChTt23oY:-MRXpDpG7QVU95sBWN7P:bs7wumx) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/main.tf#L75)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

These egress rules for `bll_ephemeral` and `ntp` belong under the `mgmt_plane` security group; not `test_plane`.
</blockquote></details>

Done. 
___
*[main.tf, line 110 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRXA0SX3xXexLCNO0Fl:-MR_JAXt-gRea7-RmyQR:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/main.tf#L110)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

Isn't variable declared as "var.mgmt_plane_subnet"?
</blockquote></details>

Done.
___
*[main.tf, line 125 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRXArLc192IwqXt5K-E:-MR_JMsm6StuysvmaSQc:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-az [...]

2021-01-21 17:08 UTC, jhiga requested changes
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1)* status: all files reviewed, 22 unresolved discussions (waiting on @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[variables.tf, line 72 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWh6kh3mZa7OMSczFs:-MR_tzuu31nxhrQWt7-d:b-m2ujyv) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/variables.tf#L72)):*
<details><summary><i>Previously, radhikabhat08 (radhika bhat) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: Remove the extra `T` at the start of the description and end your sentence with a period.
___
*[variables.tf, line 76 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWhcw9Aq_HAWR5v7u6:-MR_uEq-ErktommKDEzb:b-7m8ty5) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/variables.tf#L76)):*
<details><summary><i>Previously, radhikabhat08 (radhika bhat) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: end sentences with a period.
___
*[variables.tf, line 16 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MR_rwJE761SvCK-s-bx:-MR_rwJE761SvCK-s-by:b-rpc4u) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/03d5bfc2211b551afc7a7a5fe18421f067394ed5/variables.tf#L16)):*
> ```HCL
> 
> variable "resource_group_name" {
>   description = "Provide resource group name in Azure"
> ```

Let's be consistent in the order we specify properties for variables.  It makes it easier to read.  Please adjust all variables declared in this file to follow this pattern.

Prefer this order:
```
variable <name> {
  type
  description
  default
}
```
___
*[variables.tf, line 28 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MR_rRG1EGJ03wlmldWS:-MR_rRG1EGJ03wlmldWT:b-f71o2e) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/03d5bfc2211b551afc7a7a5fe18421f067394ed5/variables.tf#L28)):*
> ```HCL
> 
> variable "enable_accelerated_networking" {
>   description = " Enable or disable accelerated networking on the network interface"
> ```

nit: remove leading space
___
*[variables.tf, line 51 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MR_tGunDbC2oJ8ediQ7:-MR_tGunDbC2oJ8ediQ8:b-1n41da) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/03d5bfc2211b551afc7a7a5fe18421f067394ed5/variables.tf#L51)):*
> ```HCL
> }
> 
> variable "mgmt_plane_subnet_name" {
> ```

Why is there `mgmt_plane_subnet_name` and `mgmt_plane_subnet_id` (same applies for `test_plane`)?

Based on your description, if I don't specify a subnet name it will create one for me.  But it's not clear what happens if I specify a subnet ID and omit subnet name.


<!-- Sent from Reviewable.io -->

2021-01-22 15:56 UTC, radhikabhat08 reviewed
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1)* status: 5 of 11 files reviewed, 21 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @rmyers808)

___
*[README.md, line 50 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRWM3c1AnF5bzJTUCx_:-MRcv0sD9foLhtN03MWg:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/fe2fa20ce31c61a7be2cb82491f8a8518d5158fe/README.md#L50)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Please remove extra space characters throughout the document
</blockquote></details>

Done.
___
*[variables.tf, line 16 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MR_rwJE761SvCK-s-bx:-MRek3P08WHzulIFEdKU:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/03d5bfc2211b551afc7a7a5fe18421f067394ed5/variables.tf#L16)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Let's be consistent in the order we specify properties for variables.  It makes it easier to read.  Please adjust all variables declared in this file to follow this pattern.

Prefer this order:
```
variable <name> {
  type
  description
  default
}
```
</blockquote></details>

Done.
___
*[variables.tf, line 51 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MR_tGunDbC2oJ8ediQ7:-MRek67V7HzOWdNaqjLQ:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/03d5bfc2211b551afc7a7a5fe18421f067394ed5/variables.tf#L51)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Why is there `mgmt_plane_subnet_name` and `mgmt_plane_subnet_id` (same applies for `test_plane`)?

Based on your description, if I don't specify a subnet name it will create one for me.  But it's not clear what happens if I specify a subnet ID and omit subnet name.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-22 21:42 UTC, jhiga approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once the trailing spaces are fixed

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-:-MRg1vwvAZW9ncPsf6el:bladaoq)* status: all files reviewed, 17 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @rmyers808)



<!-- Sent from Reviewable.io -->

2021-01-22 22:25 UTC, ltran-spirent requested changes
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1)* status: all files reviewed, 18 unresolved discussions (waiting on @jhiga, @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[variables.tf, line 34 at r4](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRgB4OG8ciUtfZ1ZnfQ:-MRgB4OH64ZgPGsIFD0A:bs41yfv) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/4eb49250ed42783ca61c3447892dfaea6d422f60/variables.tf#L34)):*
> ```HCL
> 
> variable "enable_accelerated_networking" {
>   type        = string
> ```

should be type bool


<!-- Sent from Reviewable.io -->

2021-01-24 16:19 UTC, radhikabhat08 reviewed
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1)* status: 5 of 11 files reviewed, 18 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @rmyers808)

___
*[variables.tf, line 34 at r4](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRgB4OG8ciUtfZ1ZnfQ:-MRoxXqS2fWSlNAAdoKn:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/4eb49250ed42783ca61c3447892dfaea6d422f60/variables.tf#L34)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

should be type bool
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-24 22:14 UTC, jhiga approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-:-MRqSWgBEvtxdvo8HIt3:bnfp4nl)* status: all files reviewed, 17 unresolved discussions (waiting on @ltran-spirent and @rmyers808)



<!-- Sent from Reviewable.io -->

2021-01-25 22:52 UTC, rmyers808 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 9 files at r2, 2 of 8 files at r3, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-:-MRvjNy30Riciq0eVZYa:bnfp4nl)* status: all files reviewed, 12 unresolved discussions (waiting on @ltran-spirent)



<!-- Sent from Reviewable.io -->

2021-01-26 22:07 UTC, ltran-spirent requested changes
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1)* status: all files reviewed, 12 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

___
*[variables.tf, line 34 at r4](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-MRgB4OG8ciUtfZ1ZnfQ:-MS-iuTu8YDwjdaaT8Ui:b-a2ewju) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/4eb49250ed42783ca61c3447892dfaea6d422f60/variables.tf#L34)):*
<details><summary><i>Previously, radhikabhat08 (radhika bhat) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

does not conform to defined datatypes by Hashicorp

https://www.terraform.io/docs/language/expressions/types.html

`bool`


<!-- Sent from Reviewable.io -->

2021-01-27 15:51 UTC, ltran-spirent approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/1#-:-MS3Xh7m5ULEB2Y2uc5V:bnfp4nl)* status: 10 of 11 files reviewed, 12 unresolved discussions (waiting on @jhiga, @ltran-spirent, @radhikabhat08, and @rmyers808)



<!-- Sent from Reviewable.io -->

2021-01-27 15:57 UTC, merged